### ISSUE TITLE
想要交流一下

### ISSUE THREAD

**Issue by SYKKKKKKKKKKK** [KMnO4-zx/KMnO4-zx#1]
作者您好，我目前也是HPU 研究生在读，在做LLM，NLP的内容，今日偶然看到您的相关项目<食用指南>，觉得很有趣，希望能认识交流一下。可以的话请告诉我您的联系方式，冒昧打扰。

**Comment by KMnO4-zx** [comment]
可以给我发送邮件：1021385881@qq.com
